### ISSUE TITLE
Using yomikiri with the mokuro reader website

### ISSUE THREAD

**Issue by MakkyMTC** [BlueGreenMagick/yomikiri#12]
I use Yomikiri primarily with https://reader.mokuro.app/ to read manga, but I've noticed that when I use it I have to reload the page every one to two pages, or the reader gets stuck and I can't read the sentences, and the message "_null is not an object (evaluating 't.insertBefore;)_" appears, which is something I never used to get.

![ecb7c073-188a-4c17-ad4c-ff01631c80c1](https://github.com/user-attachments/assets/197daa59-29b3-4e18-87ed-4d2ccb3de3e6)

**Comment by BlueGreenMagick** [comment]
Thanks for the report! This bug was quite a tricky one to catch.

The error should be fixed in the next update, which I expect to release within a month.

**Comment by MakkyMTC** [comment]
Awesome, thank you so much! Yes, mokuro is amazing, I've been using it all the time, and they made a huge manga catalog too: https://catalog.mokuro.moe/  I'm glad you like it! Besides mokuro I also plan on using https://reader.ttsu.app/ to read japanese ebooks, I bet it will work great with yomikiri too ^^
